### ISSUE TITLE
Expected to enqueue with global_id not working properly?

### ISSUE THREAD

**Issue by jakecraige** [gocardless/rspec-activejob#10]
I have a test that looks like this:

```ruby
      app = create(:loan_application)
      params = {
        loan_application: attributes_for(:loan_application, :loan_details)
      }

      expect { put :update, params }.
        to enqueue_a(PublishLoanApplicationJob).with(global_id(app))
```

When I run it, I get this exception:

```
expected to enqueue a PublishLoanApplicationJob with [#<RSpec::ActiveJob::Matchers::GlobalID:0x007fdd674ac828 @expected=#<LoanApplication id: 286, ...l>>], but enqueued with [{"_aj_globalid"=>"gid://app/LoanApplication/287"}]
```

What am I doing wrong? 

Using Rails 4.2.1 and ActiveJob 4.2.1

**Comment by isaacseymour** [comment]
The `LoanApplication` being enqueued has id `286` but you're expecting one with id `287` in the test, so there's something wrong with the code you're testing I think.

**Comment by jakecraige** [comment]
Yeah I just caught that. My bad. Thanks for the quick response.

I guess my recommendation now would be to make the error more clear what's wrong :) I think the `RSpec::ActiveJob::Matchers::GlobalID`.. part was throwing me off.
