### ISSUE TITLE
Support RSpec's .not_to

### ISSUE THREAD

**Issue by jakecraige** [gocardless/rspec-activejob#11]
I tried using .not_to in a test and get a NoMethodError error:

```
NoMethodError:undefined method `failure_message_when_negated' for #<RSpec::ActiveJob::Matchers::EnqueueA:0x007fce18fe1558>
```

It would be great to have the ability to assert that a job was not enqueued as well

Edit: You'll only see this exception when the test fails. So to recreate you'll need a failing test.

**Comment by isaacseymour** [comment]
#12 :boom:
