### ISSUE TITLE
Testing error handling

### ISSUE THREAD

**Issue by adarsh** [gocardless/rspec-activejob#15]
This is pretty difficult now. Anyone else find a good way to test the `rescue_from` behavior in ActiveJob?

DelayedJob has a nice `error` method hook:

```ruby
def error(job, exception)
    ExceptionService.notify(exception)
end
```

Maybe it's worth adding this to ActiveJob?

**Comment by isaacseymour** [comment]
I think you could write something like:
```ruby
class MyError < StandardError; end

class MyJob < ActiveJob::Base
  rescue_from(MyError) { |error| ExceptionService.notify(error) }
  
  def perform
    "nothing to see here"
  end
end

it "shouts about errors" do
  expect(ExceptionService).to receive(:notify).with(exception)
  allow_any_instance_of(MyJob).to receive(:perform).and_raise(MyError.new("sad times"))
  MyJob.perform_now
end
```

**Comment by adarsh** [comment]
Nice! Thank you @isaacseymour! I always forget about `allow_any_instance_of`.

I feel like this is now off-topic and I'm going to close it in favor of a patch to Rails. Feel free to re-open if someone feels like an error matcher would be helpful for these jobs.
