### ISSUE TITLE
Can only get tests to pass with before(:each) block that sets the queue_adapter to :test

### ISSUE THREAD

**Issue by mmichael0413** [gocardless/rspec-activejob#26]
I have a model concern that has an `after_create` callback (used by several models) which calls a method that enqueues a job using ActiveJob. When running my specs though, they kept failing with:

`NoMethodError: undefined method 'enqueued_jobs=' for nil:NilClass`

I'm using Ruby 2.2, Rails 4.2, ActiveJob 4.2.0, and rspec-activejob 0.5.0.

In my `test.rb` environment file: `config.active_job.queue_adapter = :test`

In `spec_helper.rb`:

```
require 'rspec/active_job'

RSpec.configure do |config|
  ...
  config.include RSpec::ActiveJob

  # clean out the queue after each spec
  config.after(:each) do
    ActiveJob::Base.queue_adapter.enqueued_jobs = []
    ActiveJob::Base.queue_adapter.performed_jobs = []
  end
  ...
end
```

It wasn't until I added the following to `spec_helper.rb` that the tests started to pass:

```
config.before(:each) do
  ActiveJob::Base.queue_adapter = :test
end
```

This doesn't make sense though, since I'm already setting the queue_adapter to :test in my `test.rb` file.

Any idea what's going on?

**Comment by isaacseymour** [comment]
I'm not sure why this would happen, but it may be worth bumping the patch version of Rails - 4.2.1 much improved the ActiveJob test adapter, among other things, so it's probably worth trying that.

**Comment by mmichael0413** [comment]
That did the trick! Thanks @isaacseymour
