### ISSUE TITLE
after_perform

### ISSUE THREAD

**Issue by dramalho** [gocardless/rspec-activejob#27]
Quick one, it seems like `after_perform` blocks inside an ActiveJob object aren't being called. I suppose it has to do with using an `Array` as a queue backend. 

Any hints on how to spec stuff that happens inside the `after_perform` , except maybe explicitly unit testing the method of course :)

cheers

**Comment by isaacseymour** [comment]
That sounds like an issue with ActiveJob's test adapter itself - this library is just some matchers to make asserting things about the test adapter easier with RSpec (i.e. testing that something enqueues the right jobs).

For testing the jobs themselves you should just be able to call `MyJob.run(*args)` with assertions before/after.

If you want to integration test the whole flow (i.e. test that a controller enqueues a job, and that executing that job does the right things all in the same test), you can set `ActiveJob::TestAdapter.perform_enqueued_jobs = true` - see [the docs for ActiveJob::TestAdapter](http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/TestAdapter.html).

**Comment by dramalho** [comment]
Lovely, I'll take a look, thanks @isaacseymour

**Comment by dramalho** [comment]
I closed this to keep the `issues` list clean, I'll still come back to you when I have a chance to figure it out :) . Thanks again
