### ISSUE TITLE
Rails 4.2.1 support

### ISSUE THREAD

**Issue by shlima** [gocardless/rspec-activejob#5]
```
expected to enqueue a FeedbackNotifierJob with [#<Feedback id: 458196469>], but enqueued with [{"_aj_globalid"=>"gid://chat/Feedback/458196469"}]
```

**Comment by isaacseymour** [comment]
Hey @shlima, sorry for not responding to this sooner - must have missed the email notification. v0.3.0 adds the `deserialize_as` matcher, which deals with exactly this :tada:
